version: '3.3'

services:
  
  images:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    volumes:
      - ".:/code"
    entrypoint: ["sh", "-c", "sleep infinity"]

  mysql:
    image: mysql:5.7.17
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./:/code
    env_file:
      - .env